### ISSUE TITLE
Issues with ./contrib/sidechain-manipulation.py after creating a New Sidechain 

### ISSUE THREAD

**Issue by JJaouadi** [ElementsProject/elements#100]
I’am using this link: https://github.com/ElementsProject/elements/blob/alpha/fedpeg-README.md 
after creating my sidechain i got an error with this command: ./elements/contrib/sidechain-manipulation.py generate-one-of-one-multisig sidechain-wallet

Error:
Traceback (most recent call last):
 File "./contrib/sidechain-manipulation.py", line 134, in <module>
   address = sidechain.getnewaddress()
 File "/home/axa-lab/sidechains/elements/contrib/../../python-bitcoinrpc/bitcoinrpc/authproxy.py", line 139, in **call**
   response = self._get_response()
 File "/home/axa-lab/sidechains/elements/contrib/../../python-bitcoinrpc/bitcoinrpc/authproxy.py", line 179, in _get_response
   http_response = self.__conn.getresponse()
 File "/usr/lib/python2.7/httplib.py", line 1136, in getresponse
   response.begin()
 File "/usr/lib/python2.7/httplib.py", line 453, in begin
   version, status, reason = self._read_status()
 File "/usr/lib/python2.7/httplib.py", line 417, in _read_status
   raise BadStatusLine(line)
httplib.BadStatusLine: ''

**Comment by gwillen** [comment]
Hi @JJaouadi! It seems like the script is having trouble talking to your sidechain daemon (e.g. alphad). From the error you're getting, it reads to me like it successfully connected to the RPC port, made a request, and got a response, but the first line of the response was blank and did not contain an HTTP status code, OR possibly the sidechain daemon disconnected instead of providing a response.

Can you check and make sure that your sidechain daemon is running, that you can make requests to it successfully using bitcoin-cli/alpha-cli or equivalent, and can you check its log for suggestive errors?

I'm happy to walk you through any of those things.

**Comment by JJaouadi** [comment]
Thank you very much for your response @gwillen :)

**Comment by JJaouadi** [comment]
Hi ! After creating my sidechain, I followed Step 6 of the Elements-Alpha README to move money into my new sidechain. After the "claim-on-sidechain" part, I run blocksign.py but I have issues with spend-from-claim command can you help me please ? 

./elements/contrib/sidechain-manipulation.py spend-from-claim 39df77389fe70ef886a54fb6450fa6183d721b6d249fa55da658e967336edef4 22E8QFoqj2ncdstsmd9TUyRkwJQPXcZMmXXbL8VAyZtGtGicKoXyVdjL8hqMjieFBSdENts9dK14pcpu6
Submitting tx to mempool...
Traceback (most recent call last):
  File "./elements/contrib/sidechain-manipulation.py", line 268, in <module>
    sidechain.sendrawtransaction(tx_hex["hex"])
  File "/home/axa-lab/sidechains/elements/contrib/../../python-bitcoinrpc/bitcoinrpc/authproxy.py", line 141, in __call__
    raise JSONRPCException(response['error'])
JSONRPCException: -26: 66: insufficient priority

Got the following error from an RPC Call:
{u'message': u'66: insufficient priority', u'code': -26}

**Comment by instagibbs** [comment]
@JJaouadi might be because the peg-in utxo was still too "new" for a free transaction.
