### ISSUE TITLE
build fails on fedora 37

### ISSUE THREAD

**Issue by grubles** [ElementsProject/elements#1204]
at commit 0a20d6e3275db765a8acc74d07e5daacefedea07
arch: ppc64le

```
  CXX      wallet/test/test_test_bitcoin-init_test_fixture.o
wallet/test/init_test_fixture.cpp: In constructor ‘InitWalletDirTestingSetup::InitWalletDirTestingSetup(const std::string&)’:
wallet/test/init_test_fixture.cpp:35:52: error: ‘std::map<std::__cxx11::basic_string<char>, boost::filesystem::path>::mapped_type’ {aka ‘class boost::filesystem::path’} has no member named ‘BOOST_FILESYSTEM_C_STR’
   35 |     std::ofstream f(m_walletdir_path_cases["file"].BOOST_FILESYSTEM_C_STR);
      |                                                    ^~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:17049: wallet/test/test_test_bitcoin-init_test_fixture.o] Error 1
make[2]: Leaving directory '/home/user/builds/elements/src'
make[1]: *** [Makefile:18581: all-recursive] Error 1
make[1]: Leaving directory '/home/user/builds/elements/src'
make: *** [Makefile:833: all-recursive] Error 1

```

**Comment by delta1** [comment]
Do you have the same issue when building bitcoin @grubles ?

**Comment by psgreco** [comment]
@grubles look at this MR https://github.com/ElementsProject/elements/pull/1142, it should include the commits for master to build. The reason it's not merged yet is because those commits will come from the "normal" merge process from Core. You can either use 22.1 (which includes almost everything in master) or cherry-pick those commits. Hopefully we'll merge the 24 codebase soon so we won't have this problem anymore

**Comment by delta1** [comment]
I did manage to build this commit with the guix build, if you just need the binary 

https://github.com/delta1/elements/releases/tag/v21.99-0a20d6e3275d

**Comment by grubles** [comment]
Just tried building bitcoind from master and it worked. `elements-22.1` tag also worked. Appreciate the explanation @psgreco.
