### ISSUE TITLE
Coinbase output maturity limits are not enforced

### ISSUE THREAD

**Issue by TheBlueMatt** [ElementsProject/elements#14]
@luke-jr notes that coinbase outputs can be claimed on alpha after the usual 6 blocks, not after the 100 block maturity requirement to spend them. This actually wont break anything and you still have to wait to claim them (due to the 144 alpha block limit), but it should be fixed.

**Comment by luke-jr** [comment]
144 alpha blocks might be before 100 testnet blocks, so it's not impossible.

**Comment by instagibbs** [comment]
Heh, this is still an issue and we've hit it in testing environments. We should fix this.

**Comment by apoelstra** [comment]
To clarify using more modern terminology

* If you start an Elements chain that allows pegin claims with fewer than 100 blocks,
* and somebody creates a Bitcoin coinbase output which pegs into that chain,
* and the user claims that pegin before 100 blocks are up,

Then (a) the pegin will be recognized as valid even though the coins backing it cannot be spent, creating a "temporary insolvency" situation, and (b) the current Liquid functionary software will actually try to spend these, creating invalid transactions until the coins mature, resulting in a DoS vector.

We haven't noticed this much in practice because all of our test (and production) networks have required ≥100 confs before claiming pegins.

**Comment by instagibbs** [comment]
#538 should solve it, going to write a test soon
