### ISSUE TITLE
import/dumpwallet needs to support blinding keys

### ISSUE THREAD

**Issue by instagibbs** [ElementsProject/elements#233]
Not sure of the best way to accomplish this. We do not want to blow away the master blinding key upon import, which could lead to loss of funds.

This would allow us to re-enable wallet-dump.py and make that functionality useful again.

**Comment by dgpv** [comment]
What was the reason for the choice that the blinding key is not derived from the master xprivkey ?

Is this because you would need to choose the derivation path for this, and that means that someone potentially could reuse the same derivation path in the future ?

That could be solved by reserving the BIP43 purpose for the blinding keys, maybe something like 0x80'BLN' (0x80424c4e), like its done for GPG by ledger, for example (https://github.com/LedgerHQ/ledger-app-openpgp-card/blob/master/doc/developper/gpgcard3.0-addon.rst#deterministic-key-derivation)

It seems to me that if the blinding derivation key would itself be derived from xprivkey, and not randomly-generated, the task of backing up the wallet would be greatly simplified (you would only need to backup master xpriv)

Given that people start to talk about the possibility of adding confidential transaction support to the Bitcoin, it would be sad if Bitcoin users would need to backup two master keys instead of just one.

**Comment by instagibbs** [comment]
https://github.com/ElementsProject/elements/issues/448

IIRC the original derivation is pre-HD in Core which explains why it is the
way it is and we tell operators to backup on wallet creation.

If you want to PR a backwards compatible fix I'll ack

**Comment by instagibbs** [comment]
@dgpv our CA PR for elements rebase now includes the ability to import master blinding key, and dumps the  key in dumpwallet. So at least you can do `dumpwallet` -> `sethdseed` && `importblindingkey`

`sethdseed` is a recent RPC addition upstream.

**Comment by instagibbs** [comment]
Going to close for now, since we at least have plausible support in master.
