### ISSUE TITLE
Not a Bitcoin Core fork

### ISSUE THREAD

**Issue by dexX7** [ElementsProject/elements#3]
Given that ElementsProject is no fork of Bitcoin Core, at least in the eyes of GitHub, using the [fork compare](https://help.github.com/articles/comparing-commits-across-time/) mechanism isn't possible, which would be very handy in my opinion, to answer the question: "what exactly is the diff between EP and Core?"

As alternative to a fork, providing a reference branch could have a similar effect. Edit: I'm not sure, if https://github.com/ElementsProject/elements/commits/bitcoin is meant to be the reference branch, given the test commits.

**Comment by maaku** [comment]
This is a workaround of a known bug in github. If we forked from 'bitcoin/bitcoin' directly then references to issues and pull requests would send upstream notifications to the bitcoin repository (e.g. "This issue was referenced by ..." or "This commit fixes issue ..."). Since we intend to make full use of the issue tracker and pull request system and do no wish to spam the bitcoin repository with upstream notifications, it was necessary to structure it this way.

The 'bitcoin' branch is for running the testnet side of the two-way peg. It has new RPC commands that are necessary for the operation of the functionaries. Since the name is somewhat confusing, I will rename that branch 'mainchain' and introduce 'bitcoin-0.10' and 'bitcoin-0.11' to track the respective stable branches from the 'bitcoin/bitcoin' repository.

**Comment by dexX7** [comment]
Ah I see, thanks!
