### ISSUE TITLE
Signature hashing of transactions incorrect/surprising for multiple inputs.

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/elements#37]
CTransactionSignatureSerializer::SerializeInput() is would logically serialize the amount of the output it is spending.  Instead, it serializes the amount that the currently-being-verified input is spending.  See interpreter.cpp:1831: 

```
 // Serialize the output value 
 ::Serialize(s, nValue, nType, nVersion); 
```

That nValue is the value of the currently-being verified output.  Indeed, dumping what is actually hashed for a 2-input transaction gives:

```
# Version number
01000000
# Number of inputs
02
# Input 1.  TXID:
cc6dced8113ff403c8bd5709a4b2b457b96a16b9458e5aac99569a0f271f92e900000000
# This is the correct amount (200,000,000 satoshi):
00000000000000000000000000000000000000000000000000000000000bebc200
00
00
# Since we're checking sig for input 0, script is serialized
84
a914631ac2e12267394320198d5f8760cff167cfda0d876321027fd6b164179afe28e414325e07b1a96976cea337474f57e80dad571f1d18982a672103de31b72983bde45effa48f4f26de132e45d0ed23efba630f16008d570c9e43a168527c2102aeef54810e0c01695692f66db3cce1c08c49103656647a088454c85a2f237d9852ae
# nSequence
ffffffff
# Input 2. TXID:
fadd0818c489f9e75b3c85f875567aa1ff7b9a620aea1f18bc174b97b239b7c400000000
# This is the wrong amount, copied from above.  Should be 100,000,000 satoshi!
00000000000000000000000000000000000000000000000000000000000bebc200
00
00
# No script, since it's not the input being signed.
00
ffffffff
```

...

**Comment by gwillen** [comment]
Yeah, everything you say is true. :-( I will make sure this gets fixed one way or another before the next release -- I'm rewriting some stuff around it anyway. Thanks!

**Comment by gwillen** [comment]
@sipa As I recall, you objected strongly to the approach I originally used for signing values, which was to add the value to the CTxIn. Unfortunately it's now seeming even more like that is going to be needed if we want to be able to sign the values of all inputs we're hashing over, not just the one we're currently signing for. We could definitely try to pass them _all_ in when signing, but it's not clear they'll be as readily available.

Alternatively we could just not sign the values of the other inputs (perhaps that's what you had in mind.) But especially since we're moving towards flexibility on which inputs/outputs get signed, it would be nice not to have to skip that. (We could, I suppose, only sign the current input's value IF we are signing in default "sign-all" mode, and require the values of any other to-be-signed inputs to be directly supplied if signing in bitmask mode.)

Thoughts?

**Comment by rustyrussell** [comment]
Just hash the value for the being-consumed output after you've hashed all the inputs.

There's no reason to hash the value of the other outputs anyway; you only care that this one doesn't change, and the other outputs will get committed by the other inputs' signatures.

**Comment by instagibbs** [comment]
This seems like pre-segwit discussions... closing
