### ISSUE TITLE
Documentation question wrt alpha-README and send-to-sidechain

### ISSUE THREAD

**Issue by Christewart** [ElementsProject/elements#62]
I'm trying to figure out exactly what this line does 

``` bash
  [matt@2ca87f82dd9a bitcoin]$ ./contrib/sidechain-manipulation.py send-to-sidechain 2NCs5ufweTL8VHKNT6wrZMTkrnnmpZCy99j 1
  Sending 1 to 2N3zXjbwdTcPsJiy8sUK9FhWJhqQCxA8Jjr...
  (nonce: 94ffbf32c1f1c0d3089b27c98fd991d5)
  Sent tx with id bf01b88710b6023125379510ebd84b373bee88217c80739a1144e5e92b4ee2d0
```

The `send-to-sidechain` command leads me to believe that we are sending 1 BTC to the address `2NC...99j`, however in the logs it clearly says that the 1 BTC is being sent to `2N3...Jjr`. What is really happening here? 

Is the transfer of coins happening like this: `2N3...Jjr` is still on the test network - and the 1 BTC will be locked into this address until it is not longer being used on the sidechain. The address `2NC...99j` is the address used to represent the 1 BTC on the sidechain network until it is destroyed on the sidechain and is unlocked from `2N3..Jjr` on the regular test network?

**Comment by apoelstra** [comment]
@Christewart you've pretty much got it. Here's a more detailed explanation:

The `2NC...99j` address belongs to you, in that you are able to spend coins sent to this address. The `2N3...Jjr' address belongs to the Alpha functionaries, in that they are able to spend these coins. So `send-to-sidechain` generates this address and sends tBTC to the functionaries by spending to it.

However, this address is generated using (in part) your address `2NC...99j`. This allows the functionaries to recognize the coins, so that when you later claim them (with `sidechain-manipulation.py claim-on-sidechain`) they will know that everything is on the level. (Specifically: `claim-on-sidechain` creates a sidechain output referring to the testnet output that spent the coins to `2N3...Jjr`. It also claims that this output should be spendable on the sidechain by the owner of `2NC...99j`. This hash construction lets the functionaries be sure that this ownership claim actually comes from the person who spent to `2N3...Jjr`.)

Once this output is created, there is a bit of a waiting period, so that any reorgs in testnet that invalidated your spend to `2N3...Jjr` can be detected. After this waiting period you can spent the claimed coins on the sidechain. You do this by signing with the secret key to `2NC...99j`.

I agree the documentation needs to be clearer on this. I'll leave this issue open to track that.

**Comment by instagibbs** [comment]
alpha is extremely not supported
