### ISSUE TITLE
Rename tracksidechain for clarity?

### ISSUE THREAD

**Issue by wtogami** [ElementsProject/elements#82]
The option tracksidechain is confusing and could probably be better renamed to something closer to its purpose.  For example, @apoelstra suggested `producereorgproofs`.

Any other ideas?

**Comment by jonasnick** [comment]
A node with `tracksidechain` does actually not produce reorg-proofs, but rather double-spend proofs at the moment and in the future, reorg-proofs will only be a subset of the fraud proofs that fully validating nodes are going to produce. `OP_REORGPROOFVERIFY` is a misnomer and should be called `OP_FRAUDPROOFVERIFY`. Similarly, I suggest `producefraudproofs` instead of `producereorgproofs`.

**Comment by instagibbs** [comment]
lol
