### ISSUE TITLE
About the bulletproofs

### ISSUE THREAD

**Issue by HarvestStars** [ElementsProject/elements#874]
hi，
I wonder when will elements implement the bulletproofs?
In the [#792](https://github.com/ElementsProject/elements/issues/792), it said the bulletproofs was long deferred. Why?
And if I want to fork elements with bulletproofs implemented, what trouble will I meet?
Thanks for your advise~

**Comment by apoelstra** [comment]
Bulletproofs are deferred because they require a flag-day hardfork of the network, and because dynamic federations are a higher priority right now.

If you try to do this on your own, you will have trouble with
* There is no "standard" implementation of Bulletproofs out there; the one I implemented for secp-zkp was never reviewed and I recently redid it to change the commitment structure and set of generators.
* To communicate blinding factors from sender to receiver, we currently use the "rangeproof sidechannel" which exploits the fact that the majority of our current rangeproofs are raw random-number-generator output and therefore it is possible to use it as a stream cipher. Bulletproofs do not have such a sidechannel and will require extra transaction data be added to communicate the openings.

**Comment by apoelstra** [comment]
Closing in favor of #934
