### ISSUE TITLE
Revalidating blocks that fail due to mainchain staleness appears to be broken

### ISSUE THREAD

**Issue by allenpiscitello** [ElementsProject/elements#891]
This has come up a few times and is worth investigating to ensure this behavior is working.

Observed behavior:

There's a pegin in the mainchain. The mainchain is not synchronized on a machine that is running Elements, such that the pegin is not mature enough. When the sidechain is validated with a claimpegin, the block is marked invalid. The mainchain catches up but the block is never re-validated and the sidechain is stuck on the block prior to the pegin.

Expected behavior:
As long as Elements is not set with -recheckpeginblockinterval=0, invalid blocks should be reprocessed every n seconds (120 by default, based on this setting). Once the mainchain is synched sufficiently, the block will be reevaluated.

See:  https://github.com/ElementsProject/elements/blob/c0e0e0a9d541ac9fcb04ebdb484a4b9ab9a4620b/src/validation.cpp#L5275

This can be worked around by manually calling reconsiderblock on the invalid block (observed twice to succeed, although this should be automatically done).

**Comment by stevenroose** [comment]
Yeah this logic is very non-trivial. Because it fundamentally breaks with an upstream invariant: that a block is either always valid or always invalid. So even if the retry logic works effectively, without any further changes to the initial sync process etc, it will still result in a ton of ugly log messages about blocks being marked invalid and then having to go over the entire header chain and reconsidering all blocks.

But yeah, we should make sure the retry logic works, of course. I think a lead could be to check what happens when an entire chain of blocks is marked invalid and just the oldest one is reconsidered. I don't recall the actual logic, but it might be that we have to go over all child blocks and reconsider them as well.

**Comment by allenpiscitello** [comment]
The way this seems to work (in practice in a federated properly working chain) is that it just stalls at the invalid block. So there is never a chain of blocks to reconsider, just a single one, it fails due to an invalid pegin, which might become valid in the future (once Bitcoin is properly synched).

Given the number of pegins have increased in Liquid, this seems more important now.

**Comment by apoelstra** [comment]
Will be fixed by #1022 (forward-port #1030)
