### ISSUE TITLE
Python example mentioned in developers guide gives an error

### ISSUE THREAD

**Issue by prayank23** [ElementsProject/elements#907]
Example: https://docs.blockstream.com/liquid/app-examples/app-examples-index.html#python

Error: `An Exception occured: 'decimal.Decimal' object is not subscriptable`

**Comment by prayank23** [comment]
`elementsd --testnet --prune=1 --server=1 --rpcuser=user1 --rpcpassword=password1 --rpcport=18332`

![image](https://user-images.githubusercontent.com/13405205/92314734-765e2d00-eff9-11ea-884b-0f390fa015cf.png)

![image](https://user-images.githubusercontent.com/13405205/92314759-b0c7ca00-eff9-11ea-941f-f36fcb7788e0.png)

**Comment by prayank23** [comment]
Issue is resolved by changing line 13 with `print(result ["balance"])`

**Comment by wintercooled** [comment]
The issue arose because you were not connecting to elementsregtest network I think but "testnet". [Here](https://elementsproject.org/elements-code-tutorial/working-environment) it point to the config file that is [here](https://github.com/ElementsProject/elements/blob/master/contrib/assets_tutorial/elements1.conf) -the default config files you can use for the example you ran.

Basically - you need:

```
chain=elementsregtest
```

...in elements.conf in order to run in the equivalent of bitcoin "regtest" mode.

If you use "regtest" it will try connecting to a network that won't display bitcoin as an asset in balance because there is only one (bitcoin). If connected to elementsregtest you will get bitcoin as a key under balance.

**Comment by amimahd** [comment]
Hello, I am happy to be by your side in this field
