### ISSUE TITLE
Serialization question

### ISSUE THREAD

**Issue by BlockMechanic** [ElementsProject/elements#909]
I noticed that in

https://github.com/ElementsProject/elements/blob/58bf5653ed30d1afbda6f93ba2d0ab30647496fc/src/script/interpreter.cpp#L1541

the witness field is not serialized, is this intentional or an oversight? I ask because comment on class declaration states 

> Wrapper that serializes like CTransaction, but with the modifications required for the signature hash done in-place.

And in elements mode, in CTransaction, witness is serialized.

**Comment by apoelstra** [comment]
It was intentional that we don't sign witness data, yes, though I agree that the comment is not clear about this.

I think in general, the legacy sighash in Bitcoin wasn't super well-designed, and our modifications for Elements were not super well-designed either :). In both cases the segwit v0 sighash is simpler and saner (and v1 will be saner still).
